/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3;

import java.awt.Component;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jhonson
 */
public class Configuracion extends javax.swing.JFrame {
    String DireccionTXT=null;
    Grafo Mapa;
    int [] Cantidades;

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        Mapa = new Grafo();
        Cantidades =new int [3];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Configuracíon");

        jLabel2.setText("Repartidores:");

        jLabel3.setText("Máximo  de  minutos:");

        jLabel4.setText("Máximo  de  pedidos:");

        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cargar mapa");

        jButton2.setText("Iniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel5)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jButton2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser buscador = new JFileChooser();
        buscador.setCurrentDirectory(new java.io.File("."));
        FileNameExtensionFilter filtroImagen=new FileNameExtensionFilter("TXT","txt");
        buscador.setFileFilter(filtroImagen);
        buscador.setDialogTitle("Seleccione el mapa");
        if (buscador.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            DireccionTXT= buscador.getSelectedFile().toString();
            System.out.print(DireccionTXT);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Component frame = null;
        // TODO add your handling code here:
        if("".equals(jTextField1.getText())|"".equals(jTextField2.getText()) | "".equals(jTextField3.getText())){
            JOptionPane.showMessageDialog(frame,"Por favor ingrese los datos solicitados");
            return;
        }
        try{
            Cantidades[0]=Integer.parseInt(jTextField1.getText());
            Cantidades[2]=Integer.parseInt(jTextField2.getText());
            Cantidades[1]=Integer.parseInt(jTextField3.getText());
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(frame,"Por favor ingrese un numero entero");
            return;
        }
        if(DireccionTXT==null){
            JOptionPane.showMessageDialog(frame,"Por favor ingrese un mapa");
        }
        
        CargarMapaGrafo();
        PanelCentral Panel = new PanelCentral();
        Panel.setDatos(Mapa, Cantidades);
        Panel.setVisible(true);
        VentanaMapa M =new VentanaMapa(Mapa);
        M.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void CargarMapaGrafo(){
        Mapa.setTamañoMaximo(10);
        Mapa.AgregarNodo(1, "Sanjose", "direcion");
        Mapa.AgregarNodo(301, "Heredia", "direcion");
        Mapa.AgregarNodo(302, "Limon", "direcion");
        Mapa.AgregarNodo(303, "Cartago", "direcion");
        Mapa.AgregarNodo(304, "Siquirres", "direcion");
        Mapa.AgregarNodo(101, "Orotina", "direcion");
        Mapa.AgregarNodo(102, "Parrita", "direcion");
        Mapa.AgregarNodo(103, "Gguna", "direcion");
        Mapa.AgregarNodo(307, "puebla", "direcion");
        Mapa.AgregarNodo(308, "hola", "direcion");
        Mapa.RelacionarNodo(301, 302, 10);
        Mapa.RelacionarNodo(301, 303, 10);
        Mapa.RelacionarNodo(301, 304, 10);
        Mapa.RelacionarNodo(301, 102, 40);
        Mapa.RelacionarNodo(303, 302, 1);
        Mapa.RelacionarNodo(303, 301, 11);
        Mapa.RelacionarNodo(303, 307, 50);
        Mapa.RelacionarNodo(304, 307, 10);
        Mapa.RelacionarNodo(307, 308, 20);
        //g.Imprimir();
        //Mapa.RutaCorta(301,308);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
