/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3;

import java.util.Arrays;

/**
 *
 * @author jhonson
 */
public class PanelCentral extends javax.swing.JFrame implements Runnable {
    Grafo Mapa;
    DoublyLinkedList<Pedido> ColaPedidos;
    int [] Cantidades;
    Thread temporizador;
    

    /**
     * Creates new form PanelCentral
     */
    public PanelCentral() {
        initComponents();
        ColaPedidos= new DoublyLinkedList<>();
        temporizador = new Thread(this);
        temporizador.start();
        
    }
    
    public void setDatos(Grafo Mapa, int [] Cantidades){
        this.Mapa=Mapa;
        this.Cantidades=Cantidades;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Panel Central");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(489, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        Thread ct = Thread.currentThread();
        while(ct == temporizador) {  
           RecibirMail CorreoR = new RecibirMail();
           CorreoR.conectar();
           if(CorreoR.getDatos().length!=0){
               System.out.println(CorreoR.getDatos()[2]);
               System.out.println(CorreoR.getDatos()[3]);
               Pedido P = new Pedido(CorreoR.getDatos()[0] ,CorreoR.getDatos()[1],convetir(CorreoR.getDatos()[2]),convetir(CorreoR.getDatos()[2]));
               ColaPedidos.append(P);
           }

            try {
                Thread.sleep(1000*15);
                }catch(InterruptedException e) {}

        }

        
    }
    
    public int convetir(String re){
        char [] ch = re.toCharArray();
        String Resul="";
        for(char i:ch){
            try{
            int n =Integer.parseInt(String.valueOf(i));
            Resul+=n;
            }
            catch(NumberFormatException e){}
        }
        return Integer.parseInt(Resul);
    }
    
}
